# Training Configuration for Raag Classifier

# Random seed for reproducibility
random_seed: 42

# Data paths
# If you have all files in data/raw/, the training script will auto-split them
# Or you can manually organize into train/val/test subdirectories
data:
  train_dir: "data/segments"  # Main data directory
  val_dir: "data/segments"    # Can be same as train_dir for auto-split
  test_dir: "data/segments"   # Can be same as train_dir for auto-split
  processed_dir: "data/processed"

# Audio processing parameters
audio:
  sample_rate: 22050
  target_duration: 5.0  # seconds

# Feature extraction
features:
  use_cqt: true  # Use Constant-Q Transform (set false for Mel spectrogram)
  n_bins: 84  # Number of frequency bins (7 octaves)
  bins_per_octave: 12  # Semitone resolution
  hop_length: 512
  n_mels: 128  # For mel spectrogram (if use_cqt=false)
  n_fft: 2048  # For mel spectrogram
  include_delta: true  # Include delta features
  include_delta_delta: false

# Segmentation
segmentation:
  segment_duration: 5.0  # seconds
  overlap_duration: 2.5  # seconds
  normalize: true
  normalization_method: "peak"  # 'peak' or 'rms'

# Voice Activity Detection
vad:
  enabled: true
  use_webrtc: false
  energy_threshold: 0.02
  use_harmonic: true
  harmonic_threshold: 0.5
  min_segment_length: 0.5  # seconds

# Data augmentation
augmentation:
  enabled: true
  pitch_shift_range: [-2.0, 2.0]  # semitones
  time_stretch_range: [0.9, 1.1]  # ratio
  noise_level: 0.005
  apply_prob: 0.5  # Probability of applying augmentation

# Model architecture
model:
  type: "simple"  # Options: 'simple', 'resnet', 'crnn', 'attention_crnn'
  dropout: 0.3
  # CNN-specific
  base_channels: 64  # For ResNet
  # CRNN-specific
  rnn_hidden_size: 128
  rnn_num_layers: 2
  rnn_type: "gru"  # 'lstm' or 'gru'
  bidirectional: true

# Training parameters
training:
  epochs: 10
  batch_size: 32
  learning_rate: 0.001
  weight_decay: 0.0001
  num_workers: 0

  # Learning rate scheduling
  lr_scheduler: "plateau"  # 'plateau', 'step', 'cosine'
  lr_patience: 5  # For ReduceLROnPlateau
  lr_factor: 0.5

  # Early stopping
  early_stopping_patience: 15

  # Gradient clipping
  grad_clip: 1.0

# Validation
validation:
  val_frequency: 1  # Validate every N epochs
  save_best_only: true

# Cross-validation (optional)
cross_validation:
  enabled: false
  n_folds: 5
  stratified: true

# Output
output_dir: "outputs/experiment_1"
save_predictions: true
save_confusion_matrix: true

# Logging
logging:
  use_tensorboard: true
  log_interval: 10  # Log every N batches
  save_model_frequency: 5  # Save checkpoint every N epochs
